In [31]:
import pandas as pd
import numpy as np

# Import dataset dari lokal
DATA_PATH = r"D:\College\Matana\Semester 5\Analisis Multivariat\star_classification.csv"
cols = ["alpha", "delta", "u", "g", "r", "i", "z"]
data = pd.read_csv(DATA_PATH, usecols=cols + ["class"])
# Pisahkan variabel prediktor (X) dan variabel respon (y)
X = data.drop(columns=["class"])
y = data["class"]

# Cek ukuran data
print(X.shape)

# Cek jumlah masing-masing kelas
print(y.value_counts().sort_index())

print(X.columns.tolist())
print(X.describe().T[["mean","min","max"]])

(100000, 7)
class
GALAXY    59445
QSO       18961
STAR      21594
Name: count, dtype: int64
['alpha', 'delta', 'u', 'g', 'r', 'i', 'z']
             mean          min         max
alpha  177.629117     0.005528  359.999810
delta   24.135305   -18.785328   83.000519
u       21.980468 -9999.000000   32.781390
g       20.531387 -9999.000000   31.602240
r       19.645762     9.822070   29.571860
i       19.084854     9.469903   32.141470
z       18.668810 -9999.000000   29.383740


In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.30,
    random_state=42,
    stratify=y
)
print(X_train.shape, X_test.shape)

(70000, 7) (30000, 7)


In [33]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import (
    LinearDiscriminantAnalysis,
    QuadraticDiscriminantAnalysis
)

lda_model = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearDiscriminantAnalysis())
])
qda_model = Pipeline([
    ('scaler', StandardScaler()),
     ('model', QuadraticDiscriminantAnalysis())
])

In [34]:
lda_model.fit(X_train, y_train)
qda_model.fit(X_train, y_train)

lda_pred = lda_model.predict(X_test)
qda_pred = qda_model.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix

lda_cm = confusion_matrix(y_test, lda_pred)
qda_cm = confusion_matrix(y_test, qda_pred)

print('LDA')
print(lda_cm)
print('QDA')
print(qda_cm)

LDA
[[16145  1235   454]
 [  688  4652   348]
 [ 2990  1521  1967]]
QDA
[[16446  1259   129]
 [  752  4901    35]
 [ 4446  1851   181]]


In [36]:
from sklearn.metrics import classification_report
print('LDA REPORT')
print(classification_report(y_test, lda_pred))
print('QDA REPORT')
print(classification_report(y_test, qda_pred))

LDA REPORT
              precision    recall  f1-score   support

      GALAXY       0.81      0.91      0.86     17834
         QSO       0.63      0.82      0.71      5688
        STAR       0.71      0.30      0.43      6478

    accuracy                           0.76     30000
   macro avg       0.72      0.68      0.66     30000
weighted avg       0.76      0.76      0.74     30000

QDA REPORT
              precision    recall  f1-score   support

      GALAXY       0.76      0.92      0.83     17834
         QSO       0.61      0.86      0.72      5688
        STAR       0.52      0.03      0.05      6478

    accuracy                           0.72     30000
   macro avg       0.63      0.60      0.53     30000
weighted avg       0.68      0.72      0.64     30000



In [37]:
from sklearn.model_selection import (
    StratifiedKFold, cross_val_score
)
cv = StratifiedKFold(
    n_splits=5, shuffle=True,
    random_state=42)

lda_scores = cross_val_score(
    lda_model, X, y, cv=cv,
    scoring='accuracy')
qda_scores = cross_val_score(
    qda_model, X, y, cv=cv,
    scoring='accuracy')



In [38]:
print(lda_scores)
print(qda_scores)

[0.75455 0.7584  0.7586  0.7575  0.75595]
[0.7278  0.71605 0.71975 0.71495 0.71825]
